on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  NODE_VERSION: '10.x'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Build
        run: |
          npm ci
          npm run build -- -- --prod
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az storage blob upload-batch --account-name anthonyandalicyacouk -d '$web' -s ./dist
      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az cdn endpoint purge --content-paths  "/*" --profile-name "anthonyandalicyacouk" --name "anthonyandalicyacouk" --resource-group "anthonyandalicya.co.uk"
      - name: logout
        run: |
          az logout